language: python
python:
  - '2.7'
matrix:
  fast_finish: true
  include:
    - if: tag IS NOT present
      python: "3.6"

cache: pip
script:
  - "true"

deploy:
  - provider: pypi
    user: andrey_yantsen
    password: $PYPI_PASSWORD
    on:
      tags: true
      distributions: sdist bdist_wheel
      repo: andrey-yantsen/plexiglas
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    file_glob: true
    file: "dist/*"
    prerelease: true
    on:
      tags: true
      repo: andrey-yantsen/plexiglas
