language: python

cache: pip

stages:
  - test
  - name: deploy
    if: tag IS present

script: true

jobs:
  include:
    - python: 2.7
    - python: 3.6
    - stage: deploy
      name: "Deploy to PyPi & GitHub"
      python: 3.6
      script: .travis/prepare_deploy.sh
      deploy:
        - provider: pypi
          user: andrey_yantsen
          password: $PYPI_PASSWORD
          skip_cleanup: true
          distributions: sdist bdist_wheel
          on:
            tags: true
            repo: andrey-yantsen/plexiglas
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          skip_cleanup: true
          file_glob: true
          file: "dist/*"
          prerelease: true
          on:
            tags: true
            repo: andrey-yantsen/plexiglas
    - python: 2.7
      name: "Deploy wheel for Python 2.7 to PyPi"
      script: .travis/prepare_deploy.sh
      deploy:
      - provider: pypi
        user: andrey_yantsen
        password: $PYPI_PASSWORD
        skip_cleanup: true
        distributions: bdist_wheel
        on:
          tags: true
          repo: andrey-yantsen/plexiglas
